title: Care Computing Group
description: Care Computing Group is led by Xianghua (Sharon) Ding at the University of Glasgow.

url: https://xianghuading.github.io/Care-Computing-Group/
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
#plugins: [jekyll-paginate]
paginate: 3

navigation:
    - title: Home
      url: /index.html
    - title: People
      url: /people
    - title: Publications
      url: /publications
    - title: Join CCG
      url: /publications

social:
      email: xianghua.ding@glasgow.ac.uk
    

google_analytics: "UA-58263416-1"

disqus:
    shortname: dingx
